### ISSUE TITLE
unrecognized selector sent to class

### ISSUE THREAD

**Issue by confile** [iotize/FaceDetection#1]
I tried to run the example on my iOS7.1 iPhone5 and got the following error on start: 

```
Video started.
Features: []
2015-04-16 13:39:00.946 FaceDetection[2445:1803] +[CIFilter filterWithName:withInputParameters:]: unrecognized selector sent to class 0x38906070
2015-04-16 13:39:00.951 FaceDetection[2445:1803] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[CIFilter filterWithName:withInputParameters:]: unrecognized selector sent to class 0x38906070'
*** First throw call stack:
(0x2d962ecb 0x380fdce7 0x2d966703 0x2d9650f7 0x2d8b4058 0x44d68 0x3e8e4 0x41e38 0x42a30 0x3ccc8 0x3ce70 0x2c854c41 0x385e6d53 0x385ebcbd 0x385e8c6f 0x385ec5f1 0x385ec8dd 0x38717c17 0x38717adc)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by u0302066** [comment]
I tried to build it in xcode 6 but got an error on the last line
Value of optional type 'CIImage?' not unwrapped; did you mean to use '!' or '?'?
func videoFeed(videoFeed: VideoFeed, didUpdateWithSampleBuffer sampleBuffer: CMSampleBuffer!) {
        let filter = FaceObscurationFilter(sampleBuffer: sampleBuffer)
        filter.process()
        dispatch_async(dispatch_get_main_queue(), { () -> Void in
            self.imageView.image = UIImage(CIImage: filter.outputImage)

**Comment by ryanmasondavies** [comment]
This should be fixed now. Please open another ticket if you have further issues.
