### ISSUE TITLE
How can I test the face detection program on Xcode?

### ISSUE THREAD

**Issue by ghost** [iotize/FaceDetection#14]
Hi , I am a new xcode developer, now I am trying to build a face counting program on ios.
I saw your code on github and tried to run it , but the error appeared "Can not record", I guess that is because the program can not get access to the camera in the iphone simulator, is there any solution to this ?

**Comment by tharak** [comment]
iphone simulator does not have a camera

**Comment by ryanmasondavies** [comment]
As @tharak pointed out, there is no camera on the simulator, so this needs to be run on a device. (Thanks @tharak!)

If you're interested in detecting faces from images not taken from a camera, I'd suggest reviewing the code and seeing how to feed 'CIImage' objects in to the face detector. 😊
