### ISSUE TITLE
Working but live capture is pixelated.

### ISSUE THREAD

**Issue by tysun** [iotize/FaceDetection#18]
Thanks for your work. Updated to Swift 3 / iOS 10 and all is working. 

The pixelation is coming from  FaceObscurationFilter but is this all the app is meant to do? Anything you point the camera at is pixelated so where does the Face Detector come into play?

![img_1231](https://cloud.githubusercontent.com/assets/11150198/20456898/3a61517c-aec3-11e6-8ce8-00c5ffd91b23.PNG)

**Comment by jacktuck** [comment]
Same here :(

**Comment by ryanmasondavies** [comment]
Thanks to both of you - I'm aware of the issue and will fix it as soon as I get some spare time!

**Comment by ryanmasondavies** [comment]
@tysun @jacktuck This should now be working. Thank you for finding it! 😃
