### ISSUE TITLE
logo for FaceDetection

### ISSUE THREAD

**Issue by hafizahmmed** [iotize/FaceDetection#21]
Hello,
Good Day, i make a logo icon for your project.I make a 3 logo for you.Which logo do you like? If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![facedetection-01](https://user-images.githubusercontent.com/38810169/40880877-e5c505f6-66da-11e8-92f9-5f88fb3c5c3a.jpg)

**Comment by ryanmasondavies** [comment]
Hey, they look great! I think I prefer the one on the left. Could you submit a pull request to update the app icon to that?

**Comment by hafizahmmed** [comment]
thank you 

check pull request #22

**Comment by hafizahmmed** [comment]
check here source file https://drive.google.com/open?id=1FhFrfDwkf8zHPdIcO9pCwBMX1uRrEP3E
