### ISSUE TITLE
Recording ?

### ISSUE THREAD

**Issue by rscodra** [iotize/FaceDetection#4]
What's the best way we can go about recording a video from this? Including the layers that are being tracked onto the face?

**Comment by ryanmasondavies** [comment]
@sambing Probably the best way is to use `AVMutableVideoComposition` and add the resulting image frames to a track, but we'd really need #3 to be fixed first. I'll take a look into this after #3 and see if it can be made easier, as it's likely to be a common requirement.

**Comment by ryanmasondavies** [comment]
@sambing I hope you found a way to do this. 👍
